"""The board: GitHub Projects as the source of truth for Lane, Owner and Seat.

`bootstrap.sh` has created the board — the three single-select fields, the `lane:`
labels, the milestones — since before lanekeeper had a Python line in it, and no
command ever called it. This module does two things with it.

**Writing.** `lanekeeper board` generates the script's inputs from `config.yaml` — the
lanes are the configured lanes, the seats are the seats with capability cards — and
runs it. The board therefore carries the same lane names the gate enforces, and the
example configuration's layer lanes (interface, service, data, platform) are gone.

**Reading.** `BoardReader` reads every card's Lane and Seat back through `gh`, so a
lane the user set with one click on the board outranks anything parsed out of an issue
body. Reading is by the ticket number, which is the one identifier the board, the
issue list and the ticket form all share.

Every call to `gh` goes through an injected runner, as the tracker's do, so the whole
module is testable without a network, an account, or a board.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence

from . import paths
from .capabilities import CapabilityRegistry
from .config import Config
from .trackers.github_issues import CommandResult

CommandRunner = Callable[[Sequence[str]], CommandResult]

#: Where the script and its example live inside the installed package.
SCRIPT_DIR = Path(__file__).resolve().parent / "scripts"
SCRIPT = SCRIPT_DIR / "bootstrap.sh"

#: The generated inputs, under lanekeeper's own directory. Regenerated on every run.
CONF_FILENAME = "board.conf"

#: The Owner options and the labels every board gets, independent of the lanes.
OWNERS = ("senior", "junior", "unsure — needs a senior call")
FIXED_LABELS = (
    "owner: senior|5319e7|Work that needs the senior bar",
    "owner: junior|5319e7|Work inside a well-fenced lane",
    "blocked|d93f0b|Must not start yet — see the blocked-by dependency",
    "security|b60205|Touches money, auth, tenant isolation or a migration",
)
MILESTONES = (
    "Core capability|The one thing the product must do. Closes when the core path works end to end.",
    "Production safeguards|Security, observability, failure handling and cost controls.",
    "Launch blockers|Everything else that must be true before release. Not a dumping ground.",
)
LANE_LABEL_COLOUR = "1d76db"


class BoardError(RuntimeError):
    """The board could not be created or read. The message says what to do."""


@dataclass(frozen=True)
class BoardCard:
    """What the board says about one ticket."""

    ref: str
    lane: str = ""
    owner: str = ""
    seat: str = ""
    status: str = ""


def _shell_quote(value: str) -> str:
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def render_conf(config: Config, seats: Sequence[str], repo: str = "") -> str:
    """The script's inputs, from the configuration rather than a hand-kept copy.

    Lanes come from the policy file, so the board and the gate agree by construction.
    The escape-hatch option the script asks for is kept: a filer who does not know the
    lane must be able to say so rather than guess.
    """
    lanes = list(config.lanes) + ["shared — needs a senior call"]
    labels = [f"lane: {name}|{LANE_LABEL_COLOUR}|Touches the {name} lane" for name in config.lanes]
    labels.append("lane: shared|b60205|Touches files no single lane owns — needs serialising")
    labels += list(FIXED_LABELS)

    def block(items: Sequence[str]) -> str:
        return "\n".join(f"  {item}" for item in items)

    return "\n".join([
        "# Generated by 'lanekeeper board' from " + paths.display_config_path() + ".",
        "# Do not edit: change the configuration and run the command again.",
        "",
        f"REPO={_shell_quote(repo)}",
        f"PROJECT_OWNER={_shell_quote(config.board.owner)}",
        f"PROJECT_TITLE={_shell_quote(config.board.title)}",
        "",
        'LANES="', block(lanes), '"',
        "",
        'OWNERS="', block(OWNERS), '"',
        "",
        'SEATS="', block(list(seats) or ["SR1", "SR2", "JR1", "JR2"]), '"',
        "",
        'LABELS="', block(labels), '"',
        "",
        'MILESTONES="', block(MILESTONES), '"',
        "",
    ])


def write_conf(config: Config, root: Path, repo: str = "") -> Path:
    seats = CapabilityRegistry.load(root).seats()
    target = paths.home(root) / CONF_FILENAME
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_conf(config, seats, repo=repo), encoding="utf-8")
    return target


def find_bash() -> Optional[str]:
    """A bash that can run the script.

    On Windows the first `bash` on PATH is usually `System32\\bash.exe`, the Windows
    Subsystem for Linux launcher, which exits 1 without a distribution installed and
    cannot see Windows paths when one is. Git for Windows ships the bash that can, so
    its usual homes are tried first there.
    """
    if sys.platform == "win32":
        roots = [os.environ.get("ProgramFiles", r"C:\Program Files"),
                 os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"),
                 os.path.join(os.environ.get("LocalAppData", ""), "Programs")]
        for root in roots:
            for rel in (r"Git\bin\bash.exe", r"Git\usr\bin\bash.exe"):
                candidate = os.path.join(root, rel)
                if root and os.path.isfile(candidate):
                    return candidate
    return shutil.which("bash")


def bash_path(path: Path) -> str:
    """A path as bash reads it: forward slashes, which Git Bash accepts for `C:/...`."""
    return str(path).replace("\\", "/")


def script_argv(conf: Path, dry_run: bool = False, check: bool = False,
                repo: str = "") -> List[str]:
    bash = find_bash()
    if bash is None:
        raise BoardError(
            "Creating the board runs a bash script, and 'bash' is not on PATH. On "
            "Windows, install Git for Windows, which provides one.")
    if not SCRIPT.is_file():
        raise BoardError(f"The board script is missing from this installation: {SCRIPT}")
    argv = [bash, bash_path(SCRIPT), "--config", bash_path(conf)]
    if repo:
        argv += ["--repo", repo]
    if check:
        argv.append("--check")
    elif dry_run:
        argv.append("--dry-run")
    return argv


def create(config: Config, root: Path, dry_run: bool = False, check: bool = False,
           repo: str = "", launcher: Optional[Callable[[Sequence[str]], int]] = None) -> int:
    """Generates the inputs and runs the script on the user's terminal."""
    conf = write_conf(config, root, repo=repo)
    argv = script_argv(conf, dry_run=dry_run, check=check, repo=repo)
    run = launcher or (lambda a: subprocess.call(list(a), cwd=str(root)))
    return run(argv)


# -- reading ---------------------------------------------------------------------


def _subprocess_runner(root: Path) -> CommandRunner:
    def run(argv: Sequence[str]) -> CommandResult:
        res = subprocess.run(list(argv), cwd=str(root), capture_output=True, text=True,
                             encoding="utf-8", errors="replace")
        return CommandResult(res.returncode, res.stdout or "", res.stderr or "")
    return run


class BoardReader:
    """Reads Lane, Owner and Seat for every card, keyed by ticket number."""

    def __init__(self, settings, root: Path, gh: str = "gh",
                 runner: Optional[CommandRunner] = None):
        self.settings = settings
        self.root = Path(root)
        self.gh = gh
        self._run = runner or _subprocess_runner(self.root)

    def _call(self, argv: Sequence[str]) -> str:
        try:
            res = self._run(argv)
        except FileNotFoundError as exc:
            raise BoardError(
                f"The GitHub command line tool ('{self.gh}') is not installed, so I "
                f"cannot read the board.") from exc
        except OSError as exc:
            raise BoardError(f"Could not run '{' '.join(argv)}': {exc}") from exc
        if res.returncode != 0:
            detail = res.stderr.strip()
            hint = ""
            if "project" in detail.lower() and "scope" in detail.lower():
                hint = " Run: gh auth refresh -s project,read:project"
            raise BoardError(
                f"Reading the board failed: {detail or 'gh exited ' + str(res.returncode)}."
                + hint)
        return res.stdout

    def _owner_argv(self) -> List[str]:
        return ["--owner", self.settings.owner] if self.settings.owner else ["--owner", "@me"]

    def project_number(self) -> int:
        """The board with the configured title, by number. Absent is an error that says so."""
        out = self._call([self.gh, "project", "list", *self._owner_argv(),
                          "--format", "json", "--limit", "200"])
        try:
            data = json.loads(out or "{}")
        except ValueError as exc:
            raise BoardError(f"The board list from gh was not JSON: {exc}") from exc
        for project in data.get("projects", []) or []:
            if str(project.get("title", "")) == self.settings.title:
                return int(project["number"])
        raise BoardError(
            f"There is no board called '{self.settings.title}' for "
            f"{self.settings.owner or 'this account'}. Run 'lanekeeper board' to create "
            f"it, or set board.title to the board you use.")

    def cards(self) -> Dict[str, BoardCard]:
        number = self.project_number()
        out = self._call([self.gh, "project", "item-list", str(number),
                          *self._owner_argv(), "--format", "json", "--limit", "1000"])
        try:
            data = json.loads(out or "{}")
        except ValueError as exc:
            raise BoardError(f"The card list from gh was not JSON: {exc}") from exc
        return parse_items(data.get("items", []) or [])


def parse_items(items: Sequence[dict]) -> Dict[str, BoardCard]:
    """The cards out of `gh project item-list --format json`.

    gh writes each single-select field as a top-level key named after the field in
    lower case, next to the `content` block that names the issue. Both spellings of
    each field are read, because the field names are the user's and the board may be
    older than this code.
    """
    cards: Dict[str, BoardCard] = {}
    for item in items:
        content = item.get("content") or {}
        number = content.get("number")
        if number is None:
            continue
        ref = str(number)

        def field(name: str) -> str:
            for key in (name.lower(), name, name.capitalize()):
                value = item.get(key)
                if isinstance(value, str) and value.strip():
                    return value.strip()
            return ""

        cards[ref] = BoardCard(ref=ref, lane=field("lane"), owner=field("owner"),
                               seat=field("seat"), status=field("status"))
    return cards


def render_cards(cards: Dict[str, BoardCard]) -> str:
    if not cards:
        return "The board has no cards yet."
    lines = ["Ticket   Lane                 Owner     Seat   Status", "-" * 60]
    for ref in sorted(cards, key=lambda r: int(r) if r.isdigit() else 0):
        c = cards[ref]
        lines.append(f"#{ref:<7} {c.lane or '-':<20} {c.owner or '-':<9} "
                     f"{c.seat or '-':<6} {c.status or '-'}")
    blank = [r for r, c in cards.items() if not c.lane]
    if blank:
        lines += ["", f"{len(blank)} card(s) have no Lane: "
                  + ", ".join(f"#{r}" for r in sorted(blank)[:10])
                  + ". Set it on the board; a card with no lane belongs to nobody."]
    return "\n".join(lines)
