"""Environment and runtime state isolation."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, Optional
from .config import Config
from .state import AgentState


class EnvironmentManager:
    def __init__(self, config: Config):
        self.config = config

    def generate_env_vars(self, agent: AgentState) -> Dict[str, str]:
        env_vars: Dict[str, str] = {
            "AGENT_ID": agent.id,
            "AGENT_NAME": agent.name,
            "AGENT_SEAT": agent.seat,
            "AGENT_LANE": agent.lane,
            "AGENT_TASK": agent.task,
        }

        # Port mapping
        for category, port_val in agent.ports.items():
            key = category.upper()
            env_vars[f"{key}_PORT"] = str(port_val)
            if category == "backend":
                env_vars["PORT"] = str(port_val)
                env_vars["API_PORT"] = str(port_val)
            elif category == "frontend":
                env_vars["FRONTEND_PORT"] = str(port_val)
                env_vars["VITE_PORT"] = str(port_val)

        # Database isolation mapping
        if self.config.database.strategy == "per-agent":
            safe_id = agent.id.replace("-", "_")
            db_name = self.config.database.name_template.replace("${AGENT_ID}", safe_id)
            env_vars["DATABASE_NAME"] = db_name
            env_vars["DB_NAME"] = db_name

        return env_vars

    def write_agent_environment(self, worktree_path: Path, agent: AgentState) -> None:
        worktree_path.mkdir(parents=True, exist_ok=True)
        env_vars = self.generate_env_vars(agent)

        # 1. Write .env file
        env_file = worktree_path / ".env"
        with open(env_file, "w", encoding="utf-8") as f:
            f.write(f"# Generated by parallel-agents for {agent.id} ({agent.name})\n")
            for k, v in sorted(env_vars.items()):
                f.write(f'{k}="{v}"\n')

        # 2. Write .lane file (seat & role declaration for AI agents)
        lane_file = worktree_path / ".lane"
        with open(lane_file, "w", encoding="utf-8") as f:
            f.write(f'SEAT="{agent.seat}"\n')
            f.write(f'ROLE="{agent.seat.lower()}"\n')
            f.write(f'LANE="{agent.lane}"\n')
            f.write(f'AGENT_ID="{agent.id}"\n')
